FROM oven/bun:latest

WORKDIR /app

ENV NODE_ENV=test \
    APP_PORT=${APP_PORT:-5005} \
    DB_HOST=${DB_HOST:-"test_db"} \
    DB_PORT=${DB_PORT:-3306} \
    DB_NAME=${DB_NAME:-"atlas_db_test"} \
    DB_USER=${DB_USER:-"test_user"} \
    DB_PASSWORD=${DB_PASSWORD:-"test_password"}

COPY package.json bun.lockb* tsconfig.json ./
RUN bun install

CMD ["bun", "test", "--watch", "--poll"]
