FROM oven/bun:latest 

WORKDIR /app

ENV NODE_ENV=development \
    APP_PORT=${APP_PORT:-3000} \
    DB_HOST=${DB_HOST:-"localhost"} \
    DB_PORT=${DB_PORT:-3306} \
    DB_NAME=${DB_NAME:-"fallback_db"} \
    DB_USER=${DB_USER:-"fallback_user"} \
    DB_PASSWORD=${DB_PASSWORD:-"fallback_password"}

COPY package.json bun.lockb* tsconfig.json ./
RUN bun install

CMD ["bun", "run", "dev"]
